# Use root/example as user/password credentials
version: '3.1'
services:
  authproxy-frontend:
    image: davidliyutong/authproxy-frontend
    restart: unless-stopped
    ports:
      - "8080:80"
    environment:
      AUTHPROXY_BACKEND_URL: "http://192.168.105.63:50032"